# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: start cmd.exe @cmd /k "echo hi && pause"
      shell: cmd

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      shell: powershell
      run: |
        [Reflection.Assembly]::LoadWithPartialName("System.Drawing")
        function screenshot([Drawing.Rectangle]$bounds, $path) {
          $bmp = New-Object Drawing.Bitmap $bounds.width, $bounds.height
          $graphics = [Drawing.Graphics]::FromImage($bmp)
          $graphics.CopyFromScreen($bounds.Location, [Drawing.Point]::Empty, $bounds.size)
          $bmp.Save($path)
          $graphics.Dispose()
          $bmp.Dispose()
        }

        $bounds = [Drawing.Rectangle]::FromLTRB(0, 0, 1000, 900)
        screenshot $bounds "C:\screenshot.png"

    - name: Upload math result for job 2
      uses: actions/upload-artifact@v1
      with:
        name: screenshot.png
        path: C:\screenshot.png

      
