# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    # Only if your repo contains the script you want screenshotted
    - uses: actions/checkout@v2

    - name: Minimize all windows
      shell: powershell
      run: |
        $shell = New-Object -ComObject "Shell.Application"
        $shell.minimizeall()

    - name: Run the command to be screenshotted
      run: start cmd.exe @cmd /k "echo hi && pause"
      shell: cmd

    - name: Take a screenshot
      shell: powershell
      run: |
        [Reflection.Assembly]::LoadWithPartialName("System.Drawing")
        function screenshot([Drawing.Rectangle]$bounds, $path) {
          $bmp = New-Object Drawing.Bitmap $bounds.width, $bounds.height
          $graphics = [Drawing.Graphics]::FromImage($bmp)
          $graphics.CopyFromScreen($bounds.Location, [Drawing.Point]::Empty, $bounds.size)
          $bmp.Save($path)
          $graphics.Dispose()
          $bmp.Dispose()
        }

        $bounds = [Drawing.Rectangle]::FromLTRB(0, 0, 1000, 900)
        screenshot $bounds "C:\screenshot.png"

    - name: Upload screenshot
      uses: actions/upload-artifact@v1
      with:
        name: screenshot.png
        path: "C:\\screenshot.png"

      
