# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Minimize all windows
        shell: powershell
        run: |
          $shell = New-Object -ComObject "Shell.Application"
          $shell.minimizeall()

      - name: Run the command to be screenshotted
        run: start cmd
        shell: powershell

      - name: Take a screenshot
        shell: powershell
        run: |
          . .\scripts\Take-ScreenShot.ps1
          Take-ScreenShot -activewindow -file "screenshot.png" -imagetype png

      - name: Upload screenshot
        uses: actions/upload-artifact@v1
        with:
          name: screenshot.png
          path: "screenshot.png"
